FROM hyperledger/sawtooth-shell:1.2

RUN apt-get update -y
RUN apt-get install -y wget \
	git \
    libssl-dev \
    libzmq3-dev \
    openssl \
    protobuf-compiler \
    python3 \
    python3-grpcio \
    python3-grpcio-tools \
    python3-pkg-resources \
    pkg-config

RUN wget https://dl.google.com/go/go1.12.1.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.12.1.linux-amd64.tar.gz
RUN mkdir /go
ENV GOPATH=/go
RUN echo $PATH
ENV PATH=$PATH:/usr/local/go/bin:/go/bin

RUN go get -u \
    github.com/btcsuite/btcd/btcec \
    github.com/golang/protobuf/proto \
    github.com/golang/protobuf/protoc-gen-go \
    github.com/golang/mock/gomock \
    github.com/golang/mock/mockgen \
    github.com/pebbe/zmq4 \
    github.com/satori/go.uuid

RUN go get github.com/hyperledger/sawtooth-sdk-go
WORKDIR /go/src/github.com/hyperledger/sawtooth-sdk-go/
RUN go generate

RUN mkdir -p /go/src/github.com/taekion-org/break-sawtooth-history
COPY . /go/src/github.com/taekion-org/break-sawtooth-history
WORKDIR /go/src/github.com/taekion-org/break-sawtooth-history
RUN make dep
